[package]
name = "vastatrix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
thiserror = "1.0.57"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
zip = "0.6.6"
