brace_style="PreferSameLine"
max_width=150
use_small_heuristics="Max"
condense_wildcard_suffixes=true
edition="2021"
empty_item_single_line=false
enum_discrim_align_threshold=80
fn_args_layout="Compressed"
fn_single_line=true
format_code_in_doc_comments=true
doc_comment_code_block_width=150
format_macro_matchers=true
format_strings=true
hex_literal_case="Upper"
indent_style="Visual"
match_arm_blocks=false
match_block_trailing_comma=true
imports_granularity="Module"
newline_style="Unix"
normalize_comments=true
normalize_doc_attributes=true
overflow_delimited_expr=true
reorder_impl_items=true
group_imports="StdExternalCrate"
struct_field_align_threshold=80
trailing_comma="Always"
unstable_features=true
use_field_init_shorthand=true
use_try_shorthand=true
version="Two"
where_single_line=true
wrap_comments=true