[package]
name = "vtx-jbridge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro = true

[dependencies]
syn = "1.0.109"
quote = "1.0.26"
vastatrix = {path = "../"}
proc-macro2 = "1.0.54"
